services:
  mysql:
    image: mysql:8.0
    container_name: cursos_ucp_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cursos_ucp
      TZ: America/Bogota
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
